### ISSUE TITLE
Verification of file value

### ISSUE THREAD

**Issue by chborntraeger** [aas-core-works/aas-core3.0-typescript#10]
According to the IDTA specification, the value of a file element must be a "PathType". This Path Type is defined as "for any string conformant to RFC808921, the "file" URI scheme (for relative and absolute file paths) applies."
In the examples, "./Specification.pdf" is also defined as a valid value.
However, the validation marks everything that does not start with the prefix: file as an error.

![image](https://github.com/aas-core-works/aas-core3.0-typescript/assets/46006486/3f361550-96af-4daa-a5de-9f5c9260de81)

**Comment by mristin** [comment]
@chborntraeger The example with the relative path in the book is unfortunately wrong. RFC 8089 does not allow relative paths, see: https://github.com/aas-core-works/aas-core-meta/issues/269.
