### ISSUE TITLE
General question regarding empty values in Validation

### ISSUE THREAD

**Issue by chborntraeger** [aas-core-works/aas-core3.0-typescript#11]
I have a general question about validating matches of data types. For many datatypes (Date, DateTime, Long, Int, ...) I get validation errors that the datatype does not match if no value is (yet) entered in the corresponding field. Are these values really not allowed, or is this still a fuzziness in the validation logic?

**Comment by mristin** [comment]
@chborntraeger the meta-model sticks to the XML specification, which, in its turn, disallows empty values for many basic data types.

For reference, please see https://www.w3.org/TR/xmlschema-2/. We model the pattern matching functions in the aas-core-meta here: https://github.com/aas-core-works/aas-core-meta/blob/396c850c18ca9a7abc9d512ca13c54a287b3f8c0/aas_core_meta/v3.py#L148 (and the following functions).

For example, https://www.w3.org/TR/xmlschema-2/#date:
> The [·lexical space·](https://www.w3.org/TR/xmlschema-2/#dt-lexical-space) of date consists of finite-length sequences of characters of the form: '-'? yyyy '-' mm '-' dd zzzzzz? where the date and optional timezone are represented exactly the same way as they are for [dateTime](https://www.w3.org/TR/xmlschema-2/#dateTime). The first moment of the interval is that represented by: '-' yyyy '-' mm '-' dd 'T00:00:00' zzzzzz? and the least upper bound of the interval is the timeline point represented (noncanonically) by: '-' yyyy '-' mm '-' dd 'T24:00:00' zzzzzz?.
