### ISSUE TITLE
De_serialize: constructor.name Not Working Due to Class Name Shortening

### ISSUE THREAD

**Issue by pawel-baran-se** [aas-core-works/aas-core3.0-typescript#15]
I encountered a problem during the minification and compilation process where class names are shortened, leading to issues with accessing constructor.name. This is causing unexpected behavior in my application.

Instead of "Property" I get "n" . I'd appreciate any insights or suggestions to help resolve this issue.

**Comment by mristin** [comment]
Hi @pawel-baran-se ,
Thanks for reporting! Could please provide a short snippet or example program so that I can visualize the issue better?

**Comment by pawel-baran-se** [comment]
Hi @mristin ,

Of course 

```typescript
//check if submodelelement
const smElementOrError = submodelElementFromJsonable(jsonable);
if (smElementOrError.value) {
   const submodelElement = smElementOrError.mustValue();
   return submodelElement.constructor.name;
}
``` 

In dev, it gets Submodel Elements right. But in prod, names get shortened for classes and functions, affecting Submodel Elements retrieval. The aim is to ensure the accurate KeyType in both dev and prod environments.

```typescript
   switch (constructorName) {
            case 'AssetAdministrationShell':
                return KeyTypes.AssetAdministrationShell;
            case 'Submodel':
                return KeyTypes.Submodel;
            case 'ConceptDescription':
                return KeyTypes.ConceptDescription;
            case 'SubmodelElementCollection':
                return KeyTypes.SubmodelElementCollection;
            case 'SubmodelElementList': 
....
```

**Comment by mristin** [comment]
Ah, I see. Basically, what needs to be done is introduce a `ModelType` enumeration for each model class and then you can switch on it.

The `as*` and `is*` need to be adapted to use this model type as well.

Is it OK for you if we implement it after Christmas?

**Comment by pawel-baran-se** [comment]
yes of course,

Thank you!

**Comment by mristin** [comment]
Hi @pawel-baran-se ,
The issue should be now fixed in the `main` branch.

Please give me some more time to fix a couple of pending issues in aas-core-meta, and propagate them to all SDKs, including this one, before I release a new minor version.

When/if you have time, please confirm that your issue has been fixed, and open this issue otherwise.

**Comment by pawel-baran-se** [comment]
Hi @mristin 
Thank you for the information.
