### ISSUE TITLE
Validation Problem in Thumbnail

### ISSUE THREAD

**Issue by chbo-ml** [aas-core-works/aas-core3.0-typescript#25]
The default thumbnail is a Resource that has to specify a valid URI.
<img width="820" alt="image" src="https://github.com/aas-core-works/aas-core3.0-typescript/assets/159545135/855d8fc9-d597-4c1d-8d59-72efb6d64476">

The validation validates the thumbnail URL to be a valid RFC URI. This is not correct.

In earlier versions default thumbnail was a File element, and this validation was correct.
<img width="817" alt="image" src="https://github.com/aas-core-works/aas-core3.0-typescript/assets/159545135/d714ef67-6129-4241-ac08-6b7f03f6cb90">

**Comment by mristin** [comment]
@chbo-ml thanks for reporting! Can you please clarify a bit -- is this a bug with aas-core-meta or a TypeScript-related issue?

(Please also double-check: do the book & the formalized meta-model coincide?)

**Comment by mristin** [comment]
Here's the formalized definition for the default thumbnail for V3.0:
https://github.com/aas-core-works/aas-core-meta/blob/cb28d189a290e4abd067fba2b040ff0df89b29ad/aas_core_meta/v3.py#L2277

Here is the definition of the resource:
https://github.com/aas-core-works/aas-core-meta/blob/cb28d189a290e4abd067fba2b040ff0df89b29ad/aas_core_meta/v3.py#L2299

The PathType validates against RFC 8089:
https://github.com/aas-core-works/aas-core-meta/blob/cb28d189a290e4abd067fba2b040ff0df89b29ad/aas_core_meta/v3.py#L1393

This seems all in line with the book snippets you posted above, doesn't it?

If it's easier for you, you can also check the HTML-rendered version:
https://aas-core-works.github.io/aas-core-meta/v3/Resource.html

**Comment by chbo-ml** [comment]
You're right, I overlooked PathType.... 
The problem is, more and more shells appear, that only have a URL to the file included ....

**Comment by mristin** [comment]
Please also see this issue / discussion: https://github.com/admin-shell-io/aas-specs/issues/299

**Comment by mristin** [comment]
Closing since not TypeScript-related.
