### ISSUE TITLE
Verification Propblem in Asset Information

### ISSUE THREAD

**Issue by chborntraeger** [aas-core-works/aas-core3.0-typescript#9]
In the validation of the AssetInformation the message 'Constraint AASd-131: Either the global asset ID shall be defined or at least one specific asset ID.' is triggered, even if the globalAssetId is set and additionally specificAssetIds are set.
However, according to the definition of the management shell, specificAssetIds are simply optional. So the message should not occur if both globalAssetId and secificAssetIDs are set.
Definition for specific asset ids in IDTA-Spec: "Additional domain-specific, typically proprietary identifier for the asset like serial number, manufacturer part ID, customer part IDs, etc"

**Comment by mristin** [comment]
@chborntraeger thank you very much for reporting this! We already had issues with formalizing this constraint, but we obviously still got it wrong.

Some of the maintainers are in the summer break, so a fix will have to wait till at least mid-August. Please apologize the delay.

**Comment by mristin** [comment]
@chborntraeger I had another look at the constraint. Here is how we formalize it:

https://github.com/aas-core-works/aas-core-meta/blob/396c850c18ca9a7abc9d512ca13c54a287b3f8c0/aas_core_meta/v3.py#L2160-L2172

```
@invariant(
    lambda self:
    (
            self.global_asset_ID is not None
            and self.specific_asset_IDs is None
    ) or (
            self.global_asset_ID is None
            and self.specific_asset_IDs is not None
            and len(self.specific_asset_IDs) >= 1
    ),
    "Constraint AASd-131: Either the global asset ID shall be defined or at least one "
    "specific asset ID."
)
```

Similar to the issue #12, the text of the constraint is obviously ambiguous. We interpreted the "either ... or" to be an exclusive or (XOR).

As this is related to the formalization, and not TypeScript, I moved to issue to aas-core-meta: https://github.com/aas-core-works/aas-core-meta/issues/278

I'll close this issue for now. Feel free to re-open if you think there is something related to TypeScript involved!
